services:
- type: web
  name: sparrowacademy-dev-minio
  healthCheckPath: /minio/health/live
  region: ohio
  runtime: image
  image:
    url: docker.io/minio/minio:latest
  dockerCommand: minio server /data --address $HOST:$PORT
  autoDeploy: false
  disk:
    name: data
    mountPath: /data
  envVars:
  - key: MINIO_ROOT_USER
    generateValue: true
  - key: MINIO_ROOT_PASSWORD
    generateValue: true
  - key: HOST
    value: "0.0.0.0"
  - key: PORT
    value: 9000
  - key: CONSOLE_PORT
    value: 9090
  - key: MINIO_BROWSER
    value: "off"
